// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iciuklrvlgmxmqznxniz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljaXVrbHJ2bGdteG1xem54bml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTQ3OTcsImV4cCI6MjA2NDU5MDc5N30.Yakg6JzAIqxau4JChFrYheSWFf9LbU9oaz0m1KYUu_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);